admin/Models/Bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public int c_id { get; set; }
        public int e_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}

admin/Models/Booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int r_id { get; set; }
        public int c_id { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Customer Customer { get; set; }
    }
}

admin/Models/Room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
            this.RoomServices = new HashSet<RoomService>();
        }
    
        public int id { get; set; }
        public string r_name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> love { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomService> RoomServices { get; set; }
    }
}

admin/Controllers/RoomController.cs
using HotelManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI.WebControls;
using cExcel = Microsoft.Office.Interop.Excel;
using System.Reflection;

namespace HotelManage.Controllers
{
    public class RoomController : Controller
    {
        private HotelManageEntities db = new HotelManageEntities();
        // GET: Room/booking
        public ActionResult Booking()
        {
            if (HomeController.userId != "admin" && HomeController.userId != "emp")
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                ViewBag.Rooms = db.Rooms.ToList();
                ViewBag.Customers = db.Customers.ToList();
                ViewBag.Bookings = db.Bookings.ToList();
                ViewBag.Employees = db.Employees.ToList();
                return View();
            }
        }
        //GET: Room/manage
        public ActionResult Manage()
        {
            if (HomeController.userId != "admin")
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                ViewBag.Rooms = db.Rooms.ToList();
                return View();
            }
        }
        //POST: Room/create
        [HttpPost]
        public ActionResult Create(int idroom, string type, float price)
        {
            try
            {
                ViewData["idroom"] = idroom;
                ViewData["type"] = type;
                ViewData["price"] = price;
                if (db.Rooms.FirstOrDefault(rs => rs.id == idroom) == null)
                {
                    Room r = new Room
                    {
                        id = idroom,
                        r_name = type,
                        price = price,
                        love = 0,
                        status = "ready"
                    };
                    db.Rooms.Add(r);
                    db.SaveChanges();
                    return RedirectToAction("Manage");
                }
                else
                {
                    TempData["msg"] = "<script>alert('Already has that room id');</script>";
                    return RedirectToAction("Manage");
                }
            }
            catch (Exception e)
            {
                throw e;
            }
        }
        //POST: Room/updateroom/{id}
        public ActionResult UpdateRoom(int id, string type, float price , string status)
        {
            ViewData["type"] = type;
            ViewData["price"] = price;
            ViewData["status"] = status;
            Room room = db.Rooms.FirstOrDefault(b => b.id == id);
                room.r_name = type;
                room.price = price;
                room.status = status;
            db.SaveChanges();
            return RedirectToAction("Manage");
        }

        //POST: Room/deleteRoomManage/{id}
        [HttpPost]
        public ActionResult DeleteRoom(int id)
        {
            Room room = db.Rooms.FirstOrDefault(b => b.id == id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Manage");
        }
        //POST: Room/booking/{id}
        [HttpPost]
        public ActionResult Booking(int id, int c_id, DateTime checkin, DateTime checkout)
        {
            ViewData["c_id"] = c_id;
            ViewData["checkin"] = checkin;
            ViewData["checkout"] = checkout;
            if(checkout < checkin || checkin < DateTime.Now)
            {
                TempData["msg"] = "<script>alert('check out time must after check in time!');</script>";
                return RedirectToAction("Booking");
            }
            Booking booking = new Booking
            {
                r_id = id,
                c_id = c_id,
                checkin = checkin,
                checkout = checkout
            };
            db.Bookings.Add(booking);
            db.SaveChanges();
            return RedirectToAction("Booking");
        }
        //POST: Room/update/{id}
        [HttpPost]
        public ActionResult UpdateBooking (int id, int c_id, DateTime checkin, DateTime checkout)
        {
            ViewData["c_id"] = c_id;
            ViewData["checkin"] = checkin;
            ViewData["checkout"] = checkout;
            if (checkout < checkin || checkin < DateTime.Now)
            {
                TempData["msg"] = "<script>alert('check out time must after check in time!');</script>";
                return RedirectToAction("Booking");
            }
            Booking booking = db.Bookings.FirstOrDefault(b => b.r_id == id && b.c_id == c_id);
            booking.checkin = checkin;
            booking.checkout = checkout;
            db.SaveChanges();
            return RedirectToAction("Booking");
        }
        //POST: Room/delete/{id}
        [HttpPost]
        public ActionResult DeleteBooking (int id)
        {
            Booking booking = db.Bookings.FirstOrDefault(b => b.r_id == id);
            List<RoomService> roomService = db.RoomServices.Where(r => r.r_id == id).ToList();
            roomService.ForEach(r =>
            {
                db.RoomServices.Remove(r);
            });
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Booking");
        }
        //POST: Room/booking/search
        [HttpPost]
        public ActionResult Search(string search)
        {
            ViewData["search"] = search;
            ViewBag.Rooms = db.Rooms.Where(r => r.r_name.Contains(search)).ToList();
            ViewBag.Customers = db.Customers.ToList();
            ViewBag.Bookings = db.Bookings.ToList();
            return View("Booking");
        }
        //POST: Room/searchroom
        [HttpPost]
        public ActionResult SearchRoom(string search)
        {
            ViewData["search"] = search;
            ViewBag.Rooms = db.Rooms.Where(r => r.r_name.Contains(search)).ToList();
            return View("Manage");
        }
        //GET: Room/bill/{id}
        public ActionResult Bill(int id, int e_id)
        {
            ViewData["e_id"] = e_id;
            _ = db.Database.ExecuteSqlCommand(@"insert into Bill(c_id,e_id,status) values (@cid,@eid,'unpaid')", new SqlParameter("@cid",id), new SqlParameter("@eid",e_id));
            db.SaveChanges();
            Bill bl = new Bill();
            bl = db.Bills.OrderByDescending(b => b.id).First();
            Booking booking = new Booking();
            booking = db.Bookings.FirstOrDefault(b => b.c_id == bl.c_id);
            ViewBag.Bill = bl;
            ViewBag.RoomServices = db.RoomServices.Where(rs => rs.r_id == booking.r_id).ToList();
            ViewBag.Booking = booking;
            return View();
        }
        //POST: Room/printBill/{id}
        [HttpPost]
        public ActionResult PrintBill(int id, string love)
        {
            ViewData["love"] = love;
            Bill bill = new Bill();
            bill = db.Bills.FirstOrDefault(b => b.id == id);
            Booking booking = new Booking();
            booking = db.Bookings.FirstOrDefault(b => b.c_id == bill.c_id);
            Room room = new Room();
            room = db.Rooms.FirstOrDefault(r => r.id == booking.r_id);
            List < RoomService > roomServices = new List<RoomService>();
            roomServices = db.RoomServices.Where(rs => rs.r_id == booking.r_id).ToList();
            cExcel.Application Excel = new cExcel.Application();
            cExcel.Workbook wb = Excel.Workbooks.Add(cExcel.XlSheetType.xlWorksheet);
            cExcel.Worksheet ws = (cExcel.Worksheet)Excel.ActiveSheet;
            Excel.Visible = true;
            ws.Cells[1, 1] = "THOUSAND STARS HOTEL";
            ws.Cells[2, 1] = "Địa Chỉ: 451 Lê Văn Việt";
            ws.Cells[3, 1] = "Điện Thoại: 0354855613";
            ws.Cells[5, 2] = "Hóa đơn chi tiết";
            ws.Cells[6, 1] = "Mã hóa đơn";
            ws.Cells[6, 2] = "Mã khách hàng";
            ws.Cells[6, 3] = "Mã nhân viên";
            ws.Cells[6, 4] = "Ngày thanh toán";
            ws.Cells[6, 5] = "Tổng";
            ws.Cells[7, 1] = bill.id;
            ws.Cells[7, 2] = bill.c_id;
            ws.Cells[7, 3] = bill.e_id;
            ws.Cells[7, 4] = bill.b_date;
            ws.Cells[7, 5] = bill.total;
            ws.Cells[9, 1] = "Dịch vụ chi tiết";
            ws.Cells[10, 1] = "STT";
            ws.Cells[10, 2] = "Tên dịch vụ";
            ws.Cells[10, 3] = "Số lượng";
            int i = 11;
            foreach(var item in roomServices)
            {
                for(int j = 1; j <= 3; j++)
                {
                    if(j == 1)
                    {
                        ws.Cells[i, 1] = i - 10;
                    }
                    else if(j == 2)
                    {
                        ws.Cells[i, j] = item.s_name;
                    }
                    else
                    {
                        ws.Cells[i, j] = item.amount;
                    }
                }
                i++;
            }
            _ = db.Database.ExecuteSqlCommand(@"delete from RoomService where r_id = @rid", new SqlParameter("@rid", booking.r_id));
            db.Bookings.Remove(booking);
            bill.status = "paid";
            if(love == "love")
            {
                room.love += 1;
            }
            db.SaveChanges();
            ViewBag.Rooms = db.Rooms.ToList();
            ViewBag.Customers = db.Customers.ToList();
            ViewBag.Bookings = db.Bookings.ToList();
            ViewBag.Employees = db.Employees.ToList();
            return View("Booking");
        }
    }
}

admin/Views/Room/Bill.cshtml
@{
    ViewBag.Title = "Bill Page";
}
@section styles{
    <link href="~/Content/styles/bill.css" rel="stylesheet" type="text/css" />
}
<p style="text-align:center; font-size: 35px; font-weight: 500">Bill</p>
<div class="bill-list">

    <div class="bill-table">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td style="font-weight: bold;">Date:</td>
                    <td>@ViewBag.Bill.b_date.ToString("dd-MM-yyyy")</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">ID Bill:</td>
                    <td>@ViewBag.Bill.id</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Customer:</td>
                    <td>@ViewBag.Bill.c_id</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Employee:</td>
                    <td>@ViewBag.Bill.e_id</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Days:</td>
                    <td>@((Convert.ToDateTime(@ViewBag.Booking.checkout) - Convert.ToDateTime(@ViewBag.Booking.checkin)).TotalDays)</td>
                </tr>
                <tr>
                    <td style="font-weight: bold;">Status:</td>
                    <td>@ViewBag.Bill.status</td>
                </tr>
            </tbody>
        </table>

    </div>
    <div class="bill-service w3-panel w3-border-left">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Name Service</th>
                    <th scope="col">Amount</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 1;}
                @foreach(var item in ViewBag.RoomServices)
                    {
                <tr>
                    <td scope="row">@i</td>
                    <td>@item.s_name</td>
                    <td>@item.amount</td>
                </tr>
                    i++;
                }
            </tbody>
        </table>

    </div>

</div>
<div class="w3-container">
    <p class="w3-right" style="font-size:18px"> Total: @ViewBag.Bill.total</p>
</div>
<div class="w3-container w3-padding">
    <button class="btn btn-success w3-right w3-border" onclick="document.getElementById('print').style.display='block'">
        Print
    </button>
</div>
<div class="w3-container">
    <div id="print" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
            <div class="w3-center">
                <i class="w3-circle w3-margin-top fas fa-credit-card" style="color: #0026ff; font-size: 32px;"></i>
            </div>
            <form class="w3-container" action=@Url.Action("PrintBill", "Room", new { id = ViewBag.Bill.id}) method="post">
                <div class="w3-section">
                    <p style="font-size:24px;font-family:'Times New Roman';font-weight:bold;">Are you satisfied with the service? Please rate </p>
                    <input class="form-check-input" style="margin-left: 10px;" type="radio" name="love" value="love" required>
                    <label class="form-check-label" style="font-size:18px; font-weight:600;font-family:'Times New Roman';">
                        Love
                    </label>
                    <input class="form-check-input" style="margin-left: 50px;" type="radio" name="love" value="unlove">
                    <label class="form-check-label" style="font-size:18px; font-weight:600;font-family:'Times New Roman';">
                        UnLove
                    </label>
                </div>
                <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Print</button>
            </form>
            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 3%;">
                <button class="btn btn-danger w3-right w3-border"
                        onclick="document.getElementById('print').style.display='none'">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>
<div style="margin-top: 265px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>

admin/Views/Room/Booking.cshtml
@{
    ViewBag.Title = "Booking Page";
}
@section styles{
    <link href="~/Content/styles/Booking.css" rel="stylesheet" type="text/css" />
}

<div class="container-fluid btnSearch">
    <form class="d-flex" role="search" action=@Url.Action("Search", "Room") method="post">
        <input class="form-control me-2"  type="search" placeholder="Search" name ="search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>

<div class="room-list">
    <p>Room List</p>
    @Html.Raw(TempData["msg"])
    <div class="room-table">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col" class="col-md-2">ID</th>
                    <th scope="col">Type</th>
                    <th scope="col" class="col-md-2">Price</th>
                    <th scope="col" class="col-md-2">Love</th>
                    <th scope="col" class="col-lg-2">Status</th>
                    <th scope="col" class="col-lg-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 1;}
                @foreach (var item in ViewBag.Rooms)
                {
                    <tr>
                        <th scope="row">@i</th>
                        <td>@item.id</td>
                        <td>@item.r_name</td>
                        <td>@item.price</td>
                        <td>@item.love</td>
                        <td>@item.status</td>
                        <td>
                            @{ bool flag = false;}
                            @foreach (var item1 in ViewBag.Bookings)
                            {
                                if (@item1.r_id == @item.id)
                                {
                                    flag = true;
                                }
                            }
                            @if (flag)
                            {
                                <i class="fa-solid fa-pen" onclick="document.getElementById('@i-fix').style.display='block'"></i>
                                <i class="fas fa-trash fa-white" onclick="document.getElementById('@i-delete').style.display='block'"></i>
                                <i class="fas fa-cash-register fa-white" onclick="document.getElementById('@i-pay').style.display='block'"></i>
                            }
                            else
                            {
                                <i class="fa-solid fa-basket-shopping" onclick="document.getElementById('@i').style.display='block'"></i>
                            }
                        </td>
                    </tr>

                    @*Thêm thông tin khách*@
                    <div class="w3-container">
                        <div id="@i" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>
                                <form class="w3-container" action="booking/@item.id" method="post">
                                    <div class="w3-section">
                                        <label for="id" style="margin-left:2%;">ID</label>
                                        <select name="c_id" id="id">
                                            @foreach (var item2 in ViewBag.Customers)
                                            {
                                                <option value="@item2.id">@item2.id - @item2.c_name</option>
                                            }
                                        </select>
                                        <br />
                                        <label style="margin-left:2%;"><b>Checkin</b></label>
                                        <input class="w3-input w3-border " style="margin-left:2%; width: 90%;" type="date" placeholder="Enter checkin" name="checkin" required>
                                        <label style="margin-left:2%;"><b>Checkout</b></label>
                                        <input class="w3-input w3-border" style="margin-left: 2%; width: 90%;" type="date" placeholder="Enter checkout" name="checkout" required>
                                    </div>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Save</button>
                                </form>

                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@i').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    @*Sửa thông tin khách*@
                    <div class="w3-container">
                        <div id="@i-fix" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>

                                <form class="w3-container" action="updatebooking/@item.id" method="post">
                                    <div class="w3-section">
                                        @foreach (var item3 in ViewBag.Bookings)
                                        {
                                            if (@item3.r_id == @item.id)
                                            {
                                                <label style="margin-left: 2%;"><b>ID</b></label>
                                                <input class="w3-input w3-border w3-margin-bottom" style="margin-left: 2%; width: 90%;" type="text" value="@item3.c_id" name="c_id" readonly>
                                                <label style="margin-left: 2%;"><b>Checkin</b></label>
                                                <input class="w3-input w3-border w3-margin-bottom" style="margin-left: 2%; width: 90%;" type="date" value="@item3.checkin.ToString("yyyy-MM-dd")" name="checkin" required>
                                                <label style="margin-left:2%;"><b>Checkout</b></label>
                                                <input class="w3-input w3-border" style="margin-left: 2%; width: 90%;" type="date" value="@item3.checkout.ToString("yyyy-MM-dd")" name="checkout" required>
                                            }
                                        }
                                    </div>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%; ">Save</button>
                                </form>
                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@i-fix').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*Xóa thông tin khách*@
                    <div class="w3-container">
                        <div id="@i-delete" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom formDltBook" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>
                                <form class="w3-container" action=@Url.Action("DeleteBooking", "Room", new { id = @item.id}) method="post">
                                    <div class="w3-section">
                                        @foreach (var item3 in ViewBag.Bookings)
                                        {
                                            if (@item3.r_id == @item.id)
                                            {
                                                <label style="margin-left: 2%;"><b>ID</b></label>
                                                <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="number" value="@item3.c_id" name="c_id" readonly>
                                                <label style="margin-left: 2%;"><b>Checkin</b></label>
                                                <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="date" value="@item3.checkin.ToString("yyyy-MM-dd")" name="checkin" readonly>
                                                <label style="margin-left: 2%;"><b>Checkout</b></label>
                                                <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="date" value="@item3.checkout.ToString("yyyy-MM-dd")" name="checkout" readonly>
                                            }
                                        }
                                    </div>
                                    <p style="color: #ff0000; font-size: 20px">*Please check again this room's services because it will also delete</p>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Delete</button>
                                </form>
                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@i-delete').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*Thông báo thanh toán*@
                    <div class="w3-container">
                        <div id="@i-pay" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom formDltBook" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>
                                @foreach (var item4 in ViewBag.Bookings)
                                {
                                    if (item4.r_id == item.id)
                                    {
                            <form class="w3-container" action=@Url.Action("Bill", "Room", new { id = @item4.c_id }) method="get">
                                <div class="w3-section" style="display:flex; justify-content:center; font-size:20px">
                                    <select name="e_id" id="id">
                                        @foreach (var item5 in ViewBag.Employees)
                                        {
                                            <option value="@item5.id">@item5.id - @item5.e_name</option>
                                        }
                                    </select>
                                </div>
                                <p>Do you want to pay this room ?</p>
                                <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">OK</button>
                            </form>
                                    }
                                }
                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@i-pay').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }
            </tbody>
        </table>
    </div>
</div>
<div style="margin-top: 345px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>