admin/Controllers/ServiceController.cs
using HotelManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;

namespace HotelManage.Controllers
{
    public class ServiceController : Controller
    {
        private HotelManageEntities db = new HotelManageEntities();
        // GET: Service/index
        public ActionResult Index()
        {
            if (HomeController.userId != "admin" && HomeController.userId != "emp")
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                List<Room> rooms = new List<Room>();
                Room r = new Room();
                db.Bookings.ToList().ForEach(b =>
                {
                    r = db.Rooms.FirstOrDefault(x => x.id == b.r_id);
                    if (r != null)
                    {
                       rooms.Add(r);
                    }
                });
                ViewBag.Rooms = rooms;
                return View();
            }
        }
        // GET: Service/ManageService
        public ActionResult ManageService()
        {
            if (HomeController.userId != "admin")
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                ViewBag.Services = db.CusServices.ToList();
                ViewBag.Employees = db.Employees.ToList();
                return View();
            }
        }
        // GET: Service/bookingservice/{id}
        public ActionResult BookingService(int id)
        {
            ViewBag.RoomServices = db.RoomServices.Where(r => r.r_id == id).ToList();
            ViewBag.Services = db.CusServices.ToList();
            return View();
        }
        // POST: Service/addservice/{id}
        [HttpPost, ActionName("AddService")]
        public ActionResult AddService(int id, string name, int amount)
        {
            ViewData["amount"] = amount;
            RoomService r = new RoomService();
            r = db.RoomServices.FirstOrDefault(s => s.r_id == id && s.s_name == name);
            if(r != null)
            {
                r.amount += amount;
                db.SaveChanges();
            }
            else
            {
                RoomService rs = new RoomService
                {
                    r_id = id,
                    s_name = name,
                    amount = amount
                };
                db.RoomServices.Add(rs);
                db.SaveChanges();
            }
            return RedirectToAction("BookingService/"+id);
        }
        //POST: Service/deleteservice/{id}
        [HttpPost, ActionName("DeleteService")]
        public ActionResult DeleteConfirm(int id, string name)
        {
            RoomService rs = db.RoomServices.FirstOrDefault(b => b.r_id == id && b.s_name == name);
            db.RoomServices.Remove(rs);
            db.SaveChanges();
            return RedirectToAction("BookingService/" + id);
        }

        //POST: Service/create
        [HttpPost]
        public ActionResult Create(string name, int empID, float price)
        {
            try
            {
                ViewData["name"] = name;
                ViewData["empID"] = empID;
                ViewData["price"] = price;
  
                CusService cs = new CusService
                {
                    s_name = name,
                    e_id = empID,
                    price = price,
                    
                };
                db.CusServices.Add(cs);
                db.SaveChanges();
                return RedirectToAction("ManageService");
            }
            catch (Exception e)
            {
                throw e;
            }
        }
        //POST: Service/update/{name}
        public ActionResult Update(string name, int empID, float price)
        {
            ViewData["empID"] = empID;
            ViewData["price"] = price;
            CusService cs = db.CusServices.FirstOrDefault(b => b.s_name == name);
            cs.e_id = empID;
            cs.price = price;
            db.SaveChanges();
            return RedirectToAction("ManageService");
        }
        //POST: Service/deleteservice/{name}
        [HttpPost]
        public ActionResult DeleteCusService(string name)
        {
            CusService cs = db.CusServices.FirstOrDefault(b => b.s_name == name);
            db.CusServices.Remove(cs);
            db.SaveChanges();
            return RedirectToAction("ManageService");
        }
        //POST: Service/searchroom
        [HttpPost]
        public ActionResult SearchRoom(string search)
        {
            ViewData["search"] = search;
            List<Room> rooms = new List<Room>();
            Room r = new Room();
            db.Bookings.ToList().ForEach(b =>
            {
                r = db.Rooms.FirstOrDefault(x => x.id == b.r_id && x.r_name.Contains(search));
                if(r != null)
                {
                   rooms.Add(r);
                }
            });
            ViewBag.Rooms = rooms;
            return View("Index");
        }
        //POST : Service/searchservice
        public ActionResult SearchService(string search)
        {
            ViewData["search"] = search;
            ViewBag.Services = db.CusServices.Where(s => s.s_name.Contains(search)).ToList();
            ViewBag.Employees = db.Employees.ToList();
            return View("ManageService");
        }
    }
}

admin/Views/Service/BookingService.cshtml
@{
    ViewBag.Title = "Service Page";
}
@section styles{
    <link href="~/Content/styles/listservice.css" rel="stylesheet" type="text/css" />
}



<div class="bigService">

    <div class="serRoom-list">
        <p>Service of room</p>
        <div class="serRoom-table">
            <table class="table ">
                <thead>
                    <tr>
                        <th scope="col">STT</th>
                        <th scope="col" class="col-md-2">Name Service</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int i = 1;}
                    @foreach (var item in ViewBag.RoomServices)
                {
                    <tr>
                        <th scope="row">@i</th>
                        <td>@item.s_name</td>
                        <td>@item.amount</td>
                        <td>
                            <i class="fas fa-trash fa-white" onclick="document.getElementById('@i-delete').style.display='block'"></i>
                        </td>
                    </tr>
                    <div class="w3-container">
                        <div id="@i-delete" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>
                                <form class="w3-container" action=@Url.Action("DeleteService", "Service", new { id = @item.r_id, name = @item.s_name }) method="post">
                                    <div class="w3-section">
                                        <label style="margin-left: 2%;"><b>Name</b></label>
                                        <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.s_name" name="s_name" readonly>
                                        <label style="margin-left: 2%;"><b>Amount</b></label>
                                        <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="number" value="@item.amount" name="amount" readonly>
                                    </div>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Delete</button>
                                </form>
                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@i-delete').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }
                </tbody>
            </table>
        </div>
    </div>


    <div class="service-list w3-panel w3-border-left">
        <p>Service List</p>
        <div class="service-table">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="col-sm-1">STT</th>
                        <th scope="col" class="col-md-2">Name Service</th>
                        <th scope="col" class="col-md-2">Employee</th>
                        <th scope="col" class="col-md-2">Price</th>
                        <th scope="col" class="col-md-2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{int j = 1;}
                    @foreach (var item in ViewBag.Services)
                 {
                    <tr>
                        <th scope="row">@j</th>
                        <td>@item.s_name</td>
                        <td>@item.e_id</td>
                        <td>@item.price</td>
                        <td><i class="fas fa-circle-plus" onclick="document.getElementById('@j-add').style.display='block'"></i></td>
                    </tr>

                    <div class="w3-container">
                        <div id="@j-add" class="w3-modal">
                            <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                                <div class="w3-center">
                                    <i class="w3-circle w3-margin-top fas fa-hotel" style="color: #0026ff; font-size: 32px;"></i>
                                </div>
                                <form class="w3-container" action=@Url.Action("AddService", "Service", new { id = @Url.RequestContext.RouteData.Values["id"], name = item.s_name }) method="post">
                                    <div class="w3-section">
                                        <label style="margin-left: 2%;"><b>Amount</b></label>
                                        <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="number" placeholder="EnterAmount" name="amount" min="1" required>
                                    </div>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Save</button>
                                </form>
                                <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                    <button class="btn btn-danger w3-right w3-border"
                                            onclick="document.getElementById('@j-add').style.display='none'">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                        j++;
                 }
                </tbody>
            </table>
        </div>
    </div>

</div>
<div style="margin-top: 310px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>

admin/Views/Service/Index.cshtml
@{
    ViewBag.Title = "List Room Service Page";
}
@section styles{
    <link href="~/Content/styles/Booking.css" rel="stylesheet" type="text/css" />
}


<div class="container-fluid btnSearch">
    <form class="d-flex" role="search" action=@Url.Action("SearchRoom", "Service") method="post">
        <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>

<div class="room-list">
    <p>Room List</p>
    <div class="room-table">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col" class="col-md-2">ID</th>
                    <th scope="col">Type</th>
                    <th scope="col" class="col-md-2">Price</th>
                    <th scope="col" class="col-lg-2">Status</th>
                    <th scope="col" class="col-lg-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 1;}
                @foreach (var item in ViewBag.Rooms)
                    {
                <tr>
                    <th scope="row">@i</th>
                    <td>@item.id</td>
                    <td>@item.r_name</td>
                    <td>@item.price</td>
                    <td>@item.status</td>
                    <td>
                        <a href="@Url.Action("BookingService", "Service", new { id = item.id })">
                            <i class="fa-solid fa-pen"></i>
                        </a>
                    </td>
                </tr>
                        i++;
                    }
            </tbody>
        </table>
    </div>
</div>
<div style="margin-top: 387px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>

admin/Views/Service/ManageService.cshtml
@{
    ViewBag.Title = "ManageService Page";
}
@section styles{
    <link href="~/Content/styles/manageservice.css" rel="stylesheet" type="text/css" />
}

<div class="container-fluid btnSearch">
    <form class="d-flex" role="search" action=@Url.Action("SearchService", "Service") method="post">
        <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <button onclick="document.getElementById('id01').style.display='block'" class="btn btn-success" style="margin-top: 1%">Add Service</button>
</div>


@*thêm thông tin*@
<div class="w3-container big-addSer">


    <div id="id01" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
            <div class="w3-center">
                <i class="w3-circle w3-margin-top fa-solid fa-user-tie" style="color: #0026ff; font-size: 32px;"></i>
            </div>
            <form class="w3-container" action="create" method="post">
                <div class="w3-section">

                    <label><b>Name</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter Name" name="name" required>
                    <label for="empID"><b>Employee ID</b></label> <br />
                    <select class="form-select" aria-label="Default select example" name="empID" id="empID">
                        @foreach (var item in ViewBag.Employees)
                        {
                        <option value="@item.id">@item.id - @item.e_name</option>
                        }
                    </select>
                    <br />
                    <label><b>Price</b></label>
                    <input class="w3-input w3-border" type="number" placeholder="Enter Price" name="price" min="1000" required>
                </div>
                <button type="submit" class="btn btn-info" style="margin-left: 0; margin-bottom: 1%;">Save</button>
            </form>

            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 0;">
                <button class="btn btn-danger w3-right w3-border"
                        onclick="document.getElementById('id01').style.display='none'">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>


<div class="cusSer-list">
    <p>Service List</p>
    <div class="cusSer-table">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="col-md-2">Employee ID</th>
                    <th scope="col" class="col-lg-2">Price</th>
                    <th scope="col" class="col-lg-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 1;}
                @foreach (var item in ViewBag.Services)
                    {
                <tr>
                    <th scope="row">@i</th>
                    <td>@item.s_name</td>
                    <td>@item.e_id</td>
                    <td>@item.price</td>
                    <td>
                        <i class="fa-solid fa-pen" onclick="document.getElementById('@i-fix').style.display='block'"></i>
                        <i class="fas fa-trash fa-white" onclick="document.getElementById('@i-delete').style.display='block'"></i>
                    </td>
                </tr>

                @*Sửa thông tin*@
                <div class="w3-container">
                    <div id="@i-fix" class="w3-modal">
                        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                            <div class="w3-center">
                                <i class="w3-circle w3-margin-top fa-solid fa-user-tie" style="color: #0026ff; font-size: 32px;"></i>
                            </div>
                            <form class="w3-container" action=@Url.Action("Update", "Service", new { name = @item.s_name}) method="post">
                                <div class="w3-section">
                                    <label style="margin-left: 2%;" for="empID"><b>Employee ID</b></label> <br />
                                    <select style="margin-left: 2%; width: 90%;" class="form-select" aria-label="Default select example" name="empID" id="empID">
                                        @foreach (var item1 in ViewBag.Employees)
                                        {
                                            if (item1.id == item.e_id)
                                            {
                                        <option value="@item1.id" selected>@item1.id - @item1.e_name</option>
                                            }
                                            else
                                            {
                                        <option value="@item1.id">@item1.id - @item1.e_name</option>
                                            }
                                        }
                                    </select>
                                    <br />
                                    <label style="margin-left: 2%;"><b>Price</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="number" value="@item.price" name="price" min="1000" required>
                                </div>
                                <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Save</button>
                            </form>
                            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                <button class="btn btn-danger w3-right w3-border"
                                        onclick="document.getElementById('@i-fix').style.display='none'">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                @*Xóa thông tin*@
                <div class="w3-container">
                    <div id="@i-delete" class="w3-modal">
                        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                            <div class="w3-center">
                                <i class="w3-circle w3-margin-top fa-solid fa-user-tie" style="color: #0026ff; font-size: 32px;"></i>
                            </div>
                            <form class="w3-container" action=@Url.Action("DeleteCusService", "Service", new { name = @item.s_name}) method="post">
                                <div class="w3-section">
                                    <label style="margin-left: 2%;"><b>Employee ID</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="tel" value="@item.e_id" name="empID" readonly>
                                    <label style="margin-left: 2%;"><b>Price</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.price" name="price" readonly>
                                </div>
                                <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Delete</button>
                            </form>
                            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                <button class="btn btn-danger w3-right w3-border"
                                        onclick="document.getElementById('@i-delete').style.display='none'">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                 i++;
               }
            </tbody>
        </table>
    </div>
</div>
<div style="margin-top: 310px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>