admin/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int id { get; set; }
        public string c_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string c_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

admin/Controllers/CustomerController.cs
using HotelManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HotelManage.Controllers
{
    public class CustomerController : Controller
    {
        private HotelManageEntities db = new HotelManageEntities();
        // GET: Customer/Index
        public ActionResult Index()
        {
            if (HomeController.userId != "admin" && HomeController.userId != "emp")
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                ViewBag.Customers = db.Customers.ToList();
                return View();
            }
        }
        //POST: Customer/create
        [HttpPost]
        public ActionResult Create(string name, string email, string phone, string address)
        {
            try
            {
                ViewData["name"] = name;
                ViewData["email"] = email;
                ViewData["phone"] = phone;
                ViewData["address"] = address;
                Customer c = new Customer
                {
                    c_name = name,
                    email = email,
                    phone = phone,
                    c_address = address,
                };
                db.Customers.Add(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw e;
            }
        }
        //POST: Customer/update/{id}
        public ActionResult Update(int id, string name, string email, string phone, string address)
        {
            ViewData["name"] = name;
            ViewData["email"] = email;
            ViewData["phone"] = phone;
            ViewData["address"] = address;
            Customer customer = db.Customers.FirstOrDefault(b => b.id == id);
            customer.c_name = name;
            customer.email = email;
            customer.phone = phone;
            customer.c_address = address;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //POST: Customer/deletecustomer/{id}
        [HttpPost]
        public ActionResult DeleteCustomer(int id)
        {
            Customer customer = db.Customers.FirstOrDefault(b => b.id == id);
            List<Booking> bookings = db.Bookings.Where(b => b.c_id == id).ToList();
            bookings.ForEach(b =>
            {
                List<RoomService> roomService = db.RoomServices.Where(r => r.r_id == id).ToList();
                roomService.ForEach(r =>
                {
                    db.RoomServices.Remove(r);
                });
            });
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //POST: Customer/search
        [HttpPost]
        public ActionResult Search(string search)
        {
            ViewData["search"] = search;    
            ViewBag.Customers = db.Customers.Where(c => c.c_name.Contains(search)).ToList();           
            return View("Index");
        }
    }
}

admin/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Manage Customer Page";
}

@section styles{
    <link href="~/Content/styles/Booking.css" rel="stylesheet" type="text/css" />
}

<div class="container-fluid btnSearch">
    <form class="d-flex" role="search" action=@Url.Action("Search", "Customer") method="post">
        <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <button onclick="document.getElementById('id01').style.display='block'" class="btn btn-success" style="margin-top: 1%">Add customer</button>
</div>

@*thêm thông tin*@
<div class="w3-container big-addCus">


    <div id="id01" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
            <div class="w3-center">
                <i class="w3-circle w3-margin-top fa-solid fa-users" style="color: #0026ff; font-size: 32px;"></i>
            </div>
            <form class="w3-container" action="create" method="post">
                <div class="w3-section">

                    <label><b>Name</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter Name" name="name" required>
                    <label><b>Email</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="email" placeholder="Enter mail" name="email" required>
                    <label><b>Phone</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="tel" placeholder="Enter Phone" name="phone" pattern="0[0-9]{9}" required>
                    <label><b>Address</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter Address" name="address" required>
                </div>
                <button type="submit" class="btn btn-info" style="margin-bottom: 1%;">Save</button>
            </form>

            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 0;">
                <button class="btn btn-danger w3-right w3-border"
                        onclick="document.getElementById('id01').style.display='none'">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

<div class="room-list">
    <p>Customer List</p>
    <div class="room-table">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">STT</th>
                    <th scope="col" class="col-sm-1">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="col-md-2">Email</th>
                    <th scope="col" class="col-lg-2">Phone</th>
                    <th scope="col" class="col-lg-2">Address</th>
                    <th scope="col" class="col-lg-2">Action</th>
                </tr>
            </thead>
            <tbody>


                @{int i = 1;}
                @foreach (var item in ViewBag.Customers)
                    {
                <tr>
                    <th scope="row">@i</th>
                    <td>@item.id</td>
                    <td>@item.c_name</td>
                    <td>@item.email</td>
                    <td>@item.phone</td>
                    <td>@item.c_address</td>
                    <td>
                        <i class="fa-solid fa-pen" onclick="document.getElementById('@i-fix').style.display='block'"></i>
                        <i class="fas fa-trash fa-white" onclick="document.getElementById('@i-delete').style.display='block'"></i>
                    </td>
                </tr>

                @*Sửa thông tin*@
                <div class="w3-container">
                    <div id="@i-fix" class="w3-modal">
                        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                            <div class="w3-center">
                                <i class="w3-circle w3-margin-top fa-solid fa-users" style="color: #0026ff; font-size: 32px;"></i>
                            </div>
                            <form class="w3-container" action="update/@item.id" method="post">
                                <div class="w3-section">
                                    <label style="margin-left: 2%;"><b>Name</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.c_name" name="name" required>
                                    <label style="margin-left: 2%;"><b>Email</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="email" value="@item.email" name="email" required>
                                    <label style="margin-left: 2%;"><b>Phone</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="tel" value="@item.phone" name="phone" pattern="0[0-9]{9}" required>
                                    <label style="margin-left: 2%;"><b>Address</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.c_address" name="address" required>
                                </div>
                                <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Save</button>
                            </form>
                            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                <button class="btn btn-danger w3-right w3-border"
                                        onclick="document.getElementById('@i-fix').style.display='none'">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                @*Xóa thông tin Khách*@
                <div class="w3-container">
                    <div id="@i-delete" class="w3-modal">
                        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="position: relative;">
                            <div class="w3-center">
                                <i class="w3-circle w3-margin-top fa-solid fa-users" style="color: #0026ff; font-size: 32px;"></i>
                            </div>
                            <form class="w3-container" action=@Url.Action("DeleteCustomer", "Customer", new { id = @item.id}) method="post">
                                <div class="w3-section">
                                    <label style="margin-left: 2%;"><b>Name</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.c_name" name="name" readonly>
                                    <label style="margin-left: 2%;"><b>Email</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="email" value="@item.email" name="email" readonly>
                                    <label style="margin-left: 2%;"><b>Phone</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="tel" value="@item.phone" name="phone" readonly>
                                    <label style="margin-left: 2%;"><b>Address</b></label>
                                    <input class="w3-input w3-border w3-margin-bottom" style="margin-left:2%; width: 90%;" type="text" value="@item.c_address" name="address" readonly>
                                </div>
                                <p style="color: #ff0000; font-size: 20px">*Booking room and services of this customer will also delete. Are you sure?</p>
                                    <button type="submit" class="btn btn-info" style="margin-left: 2%; margin-bottom: 1%;">Delete</button>
</form>
                            <div class="w3-container w3-padding" style=" width: 10%; position: absolute; bottom: 0; right: 6%;">
                                <button class="btn btn-danger w3-right w3-border"
                                        onclick="document.getElementById('@i-delete').style.display='none'">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                 i++;
               }
            </tbody>
        </table>
    </div>
</div>
<div style="margin-top: 345px"></div>
<p style="text-align: center; font-size: 20px">&copy; 2023 team 1</p>